version: "3"
services:
  ##### APP SPRING KOTLIN #####
  fca-project-cas:
    image: spring-kotlin:latest
    #    network_mode: bridge
    networks:
      - test
    container_name: spring-kotlin
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped


networks:
  test:
